### ISSUE TITLE
every ms entrys in log info.residents

### ISSUE THREAD

**Issue by FredF63** [jpawlowski/ioBroker.residents#44]
**Describe the bug**  
With acivated Timers for auto disable time and overnight time for 1 minute this log is comming every milli second

**Versions:**

-   Adapter version: 0.1.0
-   JS-Controller version: 4.0.24
-   Node version: 18.17.0
-   Operating system: docker

**Log**  

`2023-08-14 04:58:59.999 - info: residents.0 (1161) Started daily overnight reset`
`2023-08-14 04:59:00.002 - info: residents.0 (1161) Started daily absent timeout`
`2023-08-14 04:59:00.003 - info: residents.0 (1161) Started daily overnight reset`
`2023-08-14 04:59:00.003 - info: residents.0 (1161) Started daily absent timeout`
`2023-08-14 04:59:00.004 - info: residents.0 (1161) Started daily overnight reset`
`2023-08-14 04:59:00.005 - info: residents.0 (1161) Started daily absent timeout`
`2023-08-14 04:59:00.005 - info: residents.0 (1161) Started daily overnight reset`
`..`
`..`
`2023-08-14 04:59:01.000 - info: residents.0 (1161) Started daily overnight reset`
`2023-08-14 04:59:01.000 - info: residents.0 (1161) Started daily absent timeout`

**Comment by jpawlowski** [comment]
Pls upgrade your JS-controller to 5.x

**Comment by FredF63** [comment]
Understand, I wait till 5.x is available as stable

**Comment by jpawlowski** [comment]
sorry for this, I'll correct the package dependency accordingly.
