### ISSUE TITLE
Update stable version in repo from 0.1.0 to 0.1.1

### ISSUE THREAD

**Issue by GermanBluefox** [jpawlowski/ioBroker.residents#51]
# Think about update stable version to 0.1.1
**Version**: stable=**0.1.0** (87 days old) => latest=**0.1.1** (15 days old)
**Installs**: stable=**179** (86.47%), latest=**25** (12.08%), total=**207**

Click to use [developer portal](https://www.iobroker.dev/adapter/residents/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2032)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by jpawlowski** [comment]
[done](https://github.com/ioBroker/ioBroker.repositories/pull/2689)
